services:
  db:
    image: postgres:16
    container_name: event_ticketing_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_ticketing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d event_ticketing"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
